source "https://rubygems.org"

ruby "3.4.4"

gem "rails", "~> 8.0.0"

gem "bcrypt", "~> 3.1.7"
gem "bootsnap", require: false
gem "image_processing", "~> 1.2"
gem "importmap-rails"
gem "jbuilder"
gem "propshaft"
gem "puma", ">= 5.0"
gem "sqlite3", "~> 2.1"
gem "stimulus-rails"
gem "turbo-rails"
gem "tzinfo-data", platforms: %i[windows jruby]

# Dandelion specific gems
gem "mongoid"
gem "mongoid_paranoia"  # For soft deletes (same as original Dandelion)
gem "dragonfly"
gem "delayed_job_mongoid"  # For background jobs (same as original Dandelion)
gem "geocoder"  # For location-based functionality
gem "activesupport"  # For concerns and other Rails functionality

group :development do
  gem "debug", platforms: %i[mri windows], require: "debug/prelude"
  gem "web-console"
end
